server:
  port: 8080
  channel: 8000
  channel-host: 195.166.167.102

spring:
  application.name: "Tetra-Master-Server"
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/java_server}
    username: ${DB_USER:postgres}
    password: ${DB_PWD:2236}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 4
      maximumPoolSize: 20
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: true
  jpa:
    hibernate:
      ddl-auto: validate
  cache:
    type: caffeine

game:
  name-min-length: 2
  name-max-length: 16
  pswd-min-length: 4
  pswd-max-length: 16
  base-card-points-price: 5
  base-card-points: 100
  base-gil: 500
  chat-max-message-length: 60
  chat-max-history-messages: 100
  shop:
    generate-card-deck-cron: 0 0 12 * * 0 #“At 12:00 on Sunday.”
    card-generate-count: 8
    card-generate-arrow-chances: 7,12,20,33,56,64,77,100
    #card-price-for-atk-def: 100,200,300,400,500,600,700,800,900,1000,1100,1200,1300,1400,1500,1600
    #card-price-for-atk-arrows: 100,200,300,500,800,1300,2100,3400
    #card-price-for-atk-type-x: 800
    #card-price-for-atk-type-a: 1800
